# Generated by Django 4.2.5 on 2023-09-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bodega_ciudad_region_sucursal_movimientobodega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('precio_total', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('actived', models.IntegerField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('actived', models.IntegerField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('appaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('apmaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField(auto_now_add=True, null=True)),
                ('actived', models.IntegerField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ciudad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.genero')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apmaterno',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='appaterno',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empleado',
            name='actived',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.persona')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('actived', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('clave', models.CharField(max_length=10)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('precio_total', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boleta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapago'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codCargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cargo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.persona'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marca'),
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('csv', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('actived', models.IntegerField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('actived', models.IntegerField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
