# Generated by Django 4.2.5 on 2023-09-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_boleta_cargo_formapago_genero_marca_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProductoAtributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
