# Generated by Django 4.2.5 on 2023-09-29 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_atributo_valoratributo_tipoproductoatributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproductoatributo',
            name='valorAtributo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valoratributo'),
        ),
    ]
