# Generated by Django 4.2.5 on 2023-09-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tipoproductoatributo_valoratributo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ciudad',
        ),
    ]
