# Generated by Django 4.2.5 on 2023-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_valoratributo_atributo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='annovenc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mesvenc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
