# Generated by Django 4.2.5 on 2023-10-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_tarjeta_fecha_vencimiento_tarjeta_annovenc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('appaterno', models.CharField(max_length=20)),
                ('apmaterno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('ciudad', models.ForeignKey(db_column='ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ciudad')),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.DO_NOTHING, to='api.genero')),
            ],
            options={
                'db_table': 'view_cliente',
            },
        ),
    ]
