# Generated by Django 4.2.5 on 2023-10-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_boleta_direccion_factura_direccion_productocantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespacho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='numeracion',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='numeracion',
        ),
        migrations.AlterField(
            model_name='bodega',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='estadoPedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estadopedido'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='tipoDespacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipodespacho'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estadoPedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estadopedido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipoDespacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipodespacho'),
        ),
    ]
