# Generated by Django 4.2.5 on 2023-10-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_estadopedido_tipodespacho_remove_bodega_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sucursal'),
        ),
        migrations.AddField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sucursal'),
        ),
    ]
