# Generated by Django 4.2.5 on 2023-10-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_carrito_bolefactu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='bolefactu',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='carrito',
            name='envio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
