# Generated by Django 4.2.5 on 2023-10-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_bolefactu_carrito_documento_carrito_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ciudad'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numeracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
