# Generated by Django 4.2.5 on 2023-10-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sucursal_ciudad_sucursal_numeracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiropersona',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
