# Generated by Django 4.2.5 on 2023-10-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_retiropersona_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='error',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
