# Generated by Django 4.2.5 on 2023-10-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_carrito_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='error',
            field=models.CharField(default='Sin errores', max_length=150, null=True),
        ),
    ]
