# Generated by Django 4.2.5 on 2023-10-21 06:38

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_cliente_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoProducto',
            new_name='ProductoProveedor',
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=api.models.cargar_foto_producto)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
