# Generated by Django 4.2.5 on 2023-10-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_productoproducto_productoproveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.producto'),
        ),
    ]
