# Generated by Django 4.2.5 on 2023-10-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_fotoproducto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personafactura',
            name='ciudad',
        ),
    ]
