# Generated by Django 4.2.5 on 2023-10-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_personafactura_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='razonFactura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personafactura'),
        ),
    ]
