# Generated by Django 4.2.5 on 2023-10-27 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_personafactura_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasproveedor',
            name='destino',
        ),
        migrations.AddField(
            model_name='comprasproveedor',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bodega'),
        ),
        migrations.AddField(
            model_name='comprasproveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.proveedor'),
        ),
        migrations.AddField(
            model_name='comprasproveedor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dv',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comprasproveedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprasproveedor',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto'),
        ),
        migrations.CreateModel(
            name='BodegaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bodega')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.proveedor')),
            ],
        ),
    ]
