# Generated by Django 4.2.5 on 2023-11-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_comprasproveedor_estado_comprasproveedor_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasproveedor',
            name='cantidad_recibida',
            field=models.IntegerField(default=0),
        ),
    ]
