# Generated by Django 4.2.5 on 2023-11-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_comprasproveedor_cantidad_recibida'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleboleta',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='SalidaProductoBodegaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ida', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_llegada', models.DateTimeField(null=True)),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bodega')),
                ('boleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.boleta')),
                ('camionera_emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.empleado')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadopedido')),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
        ),
    ]
