# Generated by Django 4.2.5 on 2023-11-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_detalleboleta_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaproductobodegadespacho',
            name='bodega_origen',
        ),
        migrations.RemoveField(
            model_name='salidaproductobodegadespacho',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='salidaproductobodegadespacho',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetalleSalidaProductoBodegaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
        ),
    ]
