# Generated by Django 4.2.5 on 2023-11-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_salidaproductobodegadespacho_bodega_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesalidaproductobodegadespacho',
            name='salidaDespacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.salidaproductobodegadespacho'),
        ),
    ]
