# Generated by Django 4.2.5 on 2023-11-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_detallesalidaproductobodegadespacho_salidadespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaproductobodegadespacho',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario'),
        ),
    ]
