# Generated by Django 4.2.5 on 2023-11-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_salidaproductobodegadespacho_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproductobodegadespacho',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.persona'),
        ),
    ]
