insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Arica", '1', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Camarones", '1', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Putre", '1', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("General Lagos", '1', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Iquique", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Alto Hospicio", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pozo Almonte", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Camiña", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Colchane", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Huara", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pica", '2', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Antofagasta", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Mejillones", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Sierra Gorda", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Taltal", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Calama", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ollagüe", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Pedro de Atacama", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Tocopilla", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("María Elena", '3', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Copiapó", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Caldera", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Tierra Amarilla", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chañaral", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Diego de Almagro", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Vallenar", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Alto del Carmen", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Freirina", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Huasco", '4', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Serena", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coquimbo", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Andacollo", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Higuera", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Paihuano", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Vicuña", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Illapel", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Canela", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Vilos", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Salamanca", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ovalle", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Combarbalá", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Monte Patria", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Punitaqui", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Río Hurtado", '5', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Valparaíso", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Casablanca", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Concón", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Juan Fernández", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puchuncaví", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quintero", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Viña del Mar", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Isla de Pascua", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Andes", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Calle Larga", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Rinconada", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Esteban", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Ligua", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cabildo", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Papudo", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Petorca", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Zapallar", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quillota", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Calera", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Hijuelas", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Cruz", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Nogales", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Antonio", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Algarrobo", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cartagena", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("El Quisco", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("El Tabo", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Santo Domingo", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Felipe", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Catemu", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Llay-Llay", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Panquehue", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Putaendo", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Santa María", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quilpué", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Limache", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Olmué", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Villa Alemana", '6', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Rancagua", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Codegua", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coinco", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coltauco", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Doñihue", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Graneros", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Las Cabras", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Machalí", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Malloa", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Mostazal", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Olivar", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Peumo", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pichidegua", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quinta de Tilcoco", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Rengo", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Requínoa", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Vicente", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pichilemu", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Estrella", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Litueche", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Marchihue", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Navidad", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Paredones", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Fernando", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chépica", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chimbarongo", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lolol", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Nancagua", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Palmilla", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Peralillo", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Placilla", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pumanque", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Santa Cruz", '8', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Talca", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Constitución", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curepto", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Empedrado", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Maule", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pelarco", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pencahue", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Río Claro", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Clemente", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Rafael", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cauquenes", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chanco", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pelluhue", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curicó", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Hualañé", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Licantén", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Molina", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Rauco", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Romeral", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Sagrada Familia", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Teno", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Vichuquén", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Linares", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Colbún", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Longaví", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Parral", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Retiro", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Javier", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Villa Alegre", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Yerbas Buenas", '9', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chillán", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Bulnes", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chillán Viejo", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("El Carmen", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pemuco", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pinto", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quillón", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Ignacio", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Yungay", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quirihue", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cobquecura", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coelemu", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ninhue", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Portezuelo", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ránquil", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Treguaco", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Carlos", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coihueco", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ñiquén", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Fabián", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Nicolás", '10', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Concepción", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coronel", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chiguayante", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Florida", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Hualqui", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lota", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Penco", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Pedro de La Paz", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Santa Juana", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Talcahuano", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Tomé", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Hualpén", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lebu", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Arauco", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cañete", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Contulmo", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curanilahue", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Álamos", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Tirúa", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Ángeles", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Antuco", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cabrero", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Laja", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Mulchén", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Nacimiento", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Negrete", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quilaco", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quilleco", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Rosendo", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Santa Bárbara", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Tucapel", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Yumbel", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Alto Biobío", '11', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Temuco", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Carahue", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cunco", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curarrehue", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Freire", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Galvarino", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Gorbea", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lautaro", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Loncoche", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Melipeuco", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Nueva Imperial", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Padre Las Casas", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Perquenco", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pitrufquén", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pucón", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Saavedra", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Teodoro Schmidt", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Toltén", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Vilcún", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Villarrica", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cholchol", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Angol", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Collipulli", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curacautín", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ercilla", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lonquimay", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Sauces", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lumaco", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Purén", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Renaico", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Traiguén", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Victoria", '12', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Valdivia", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Corral", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lanco", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Lagos", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Máfil", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Mariquina", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Paillaco", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Panguipulli", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Unión", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Futrono", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lago Ranco", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Río Bueno", '13', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puerto Montt", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Calbuco", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cochamó", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Fresia", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Frutillar", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Los Muermos", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Llanquihue", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Maullín", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puerto Varas", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Castro", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ancud", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chonchi", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curaco de Vélez", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Dalcahue", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puqueldón", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Queilén", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quellón", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quemchi", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quinchao", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Osorno", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puerto Octay", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Purranque", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puyehue", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Río Negro", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Juan de la Costa", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Pablo", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chaitén", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Futaleufú", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Hualaihué", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Palena", '14', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Coyhaique", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lago Verde", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Aysén", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cisnes", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Guaitecas", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cochrane", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("O'Higgins", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Tortel", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Chile Chico", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Río Ibáñez", '15', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Punta Arenas", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Laguna Blanca", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Río Verde", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Gregorio", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cabo de Hornos", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Antártica", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Porvenir", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Primavera", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Timaukel", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Natales", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Torres del Paine", '16', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Santiago", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cerrillos", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Cerro Navia", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Conchalí", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("El Bosque", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Estación Central", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Huechuraba", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Independencia", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Cisterna", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Florida", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Granja", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Pintana", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("La Reina", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Las Condes", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lo Barnechea", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lo Espejo", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lo Prado", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Macul", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Maipú", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Ñuñoa", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pedro Aguirre Cerda", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Peñalolén", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Providencia", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pudahuel", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quilicura", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Quinta Normal", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Recoleta", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Renca", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Joaquín", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Miguel", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Ramón", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Vitacura", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Puente Alto", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Pirque", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San José de Maipo", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Colina", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Lampa", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Til Til", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Bernardo", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Buin", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Calera de Tango", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Paine", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Melipilla", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Alhué", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Curacaví", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("María Pinto", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("San Pedro", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Talagante", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("El Monte", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Isla de Maipo", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Padre Hurtado", '7', datetime('now'), datetime('now'));
insert INTO api_ciudad (nombre, region_id,created,edited) VALUES ("Peñaflor", '7', datetime('now'), datetime('now'));
